---
- name: Deploying snippets
  hosts: snippets
  become: yes

  tasks:
    - name: Include vaulted keys
      include_vars:
        dir: ./vaulted-keys
        files_matching: yml
  
    - name: Ensure we have docker-py installed
      pip:
        name: docker-py
        state: latest

    - name: Login to Docker for docker auth
      docker_login:
        registry: index.docker.io/v1/
        username: joe90ruggieri
        password: "{{ docker_pass }}"
        reauth: yes
        
    - name: Start Snippets Container
      docker_container:
        image: joe90ruggieri/snippets:latest
        name: snippets-joe
        state: started
        pull: true
        ports: 80:3000
        restart_policy: always

    - name: Remove unused docker images
      command: docker image prune -f -a
